version: "3"
services:

   webappwithmysql-fleetman-cont:
      image: adityagoel123/fleetman-web-with-mysql
      networks:
         - aditya-network
      ports:
         - 8084:8080
      depends_on: 
         - mysqldbpanga

   mysqldbpanga:
      image: mysql:5
      networks:
         - aditya-network
      environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_DATABASE=fleetman
      volumes:
         - aditya-volume:/var/lib/mysql

volumes:
   aditya-volume:

networks:
   aditya-network:
